name: Build and make release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        id: bump_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2
      - name: Install dependencies
        run: |
          go version
          go mod download
      - name: Run build
        run: |
          make
      - name: Archive Linux Release
        run: |
          cd ./build/linux
          tar -czf ../conch-linux.tar.gz *
      - name: Archive Windows Release
        run: |
          cd ./build/windows
          tar -czf ../conch-windows.tar.gz *
      - name: Archive Mac OS Release
        run: |
          cd ./build/macos
          tar -czf ../conch-macos.tar.gz *
      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "build/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}