name: CICD
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2
      - name: Install dependencies
        run: |
          go version
          go mod download
      - name: Run build
        run: |
          make
      - name: Archive Linux Release
        run: |
          cd ./build/linux
          tar -czf ../conch-linux.tar.gz *
      - name: Archive Windows Release
        run: |
          cd ./build/windows
          tar -czf ../conch-windows.tar.gz *
      - name: Archive Mac OS Release
        run: |
          cd ./build/macos
          tar -czf ../conch-macos.tar.gz *
      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}