name: CICD
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go mod download
      - name: Run build
        run: |
          make
      - name: Archive Linux Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'build/conch-linux.zip'
          directory: 'build/linux/'
      - name: Archive Windows Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'build/conch-windows.zip'
          directory: 'build/windows/'
      - name: Archive Mac OS Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'build/conch-macos.zip'
          directory: 'build/macos/'
      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}