name: Build and make release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2
      - name: Install dependencies
        run: |
          go version
          go mod download
      - name: Run build
        run: |
          make
      - name: Archive Linux Release
        run: |
          cd ./build/linux
          tar -czf ../conch-linux.tar.gz *
      - name: Archive Windows Release
        run: |
          cd ./build/windows
          tar -czf ../conch-windows.tar.gz *
      - name: Archive Mac OS Release
        run: |
          cd ./build/macos
          tar -czf ../conch-macos.tar.gz *
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        id: bump_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.bump_tag.outputs.new_tag }}
          prerelease: false
          title: "Build for ${{ steps.bump_tag.outputs.new_tag }}"
          files: |
            LICENSE.md
            build/conch-linux.tar.gz
            build/conch-macos.tar.gz
            build/conch-windows.tar.gz